### ISSUE TITLE
Mode Enum not recognized as int

### ISSUE THREAD

**Issue by dchurchwell** [pavlukivan/osu-py#2]
```
osu/beatmapmeta.py", line 104, in fromOsuDb
    self.playerRank[i] = osudb.readByte()
TypeError: list indices must be integers or slices, not Mode
```

The fix is quick. Just use IntEnum instead of Enum for the Mode class. I assume this issue depends on the python version, but this should be a good general fix.

```
from enum import Enum, IntEnum

class Mode(IntEnum):
```

**Comment by chayleaf** [comment]
thanks for the report, i really need to add tests to the lib

**Comment by chayleaf** [comment]
there will be some delay in this update because i'm revamping the library, hopefully it will be worth it

**Comment by chayleaf** [comment]
fixed on the dev branch
